// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bus.proto

package travelDS.bus;

public interface busAmountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:travelDS.busAmount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string busAmount = 1;</code>
   */
  java.lang.String getBusAmount();
  /**
   * <code>string busAmount = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusAmountBytes();
}
