// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bus.proto

package travelDS.bus;

public interface busDeleteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:travelDS.busDelete)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string busDelete = 1;</code>
   */
  java.lang.String getBusDelete();
  /**
   * <code>string busDelete = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusDeleteBytes();
}
