// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bus.proto

package travelDS.bus;

/**
 * Protobuf type {@code travelDS.busSpecific}
 */
public  final class busSpecific extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:travelDS.busSpecific)
    busSpecificOrBuilder {
private static final long serialVersionUID = 0L;
  // Use busSpecific.newBuilder() to construct.
  private busSpecific(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private busSpecific() {
    busSpecific_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private busSpecific(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            busSpecific_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return travelDS.bus.travelDSServiceImpl.internal_static_travelDS_busSpecific_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return travelDS.bus.travelDSServiceImpl.internal_static_travelDS_busSpecific_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            travelDS.bus.busSpecific.class, travelDS.bus.busSpecific.Builder.class);
  }

  public static final int BUSSPECIFIC_FIELD_NUMBER = 1;
  private volatile java.lang.Object busSpecific_;
  /**
   * <code>string busSpecific = 1;</code>
   */
  public java.lang.String getBusSpecific() {
    java.lang.Object ref = busSpecific_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      busSpecific_ = s;
      return s;
    }
  }
  /**
   * <code>string busSpecific = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBusSpecificBytes() {
    java.lang.Object ref = busSpecific_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      busSpecific_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBusSpecificBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, busSpecific_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBusSpecificBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, busSpecific_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof travelDS.bus.busSpecific)) {
      return super.equals(obj);
    }
    travelDS.bus.busSpecific other = (travelDS.bus.busSpecific) obj;

    boolean result = true;
    result = result && getBusSpecific()
        .equals(other.getBusSpecific());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUSSPECIFIC_FIELD_NUMBER;
    hash = (53 * hash) + getBusSpecific().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static travelDS.bus.busSpecific parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static travelDS.bus.busSpecific parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static travelDS.bus.busSpecific parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static travelDS.bus.busSpecific parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static travelDS.bus.busSpecific parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static travelDS.bus.busSpecific parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static travelDS.bus.busSpecific parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static travelDS.bus.busSpecific parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static travelDS.bus.busSpecific parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static travelDS.bus.busSpecific parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static travelDS.bus.busSpecific parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static travelDS.bus.busSpecific parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(travelDS.bus.busSpecific prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code travelDS.busSpecific}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:travelDS.busSpecific)
      travelDS.bus.busSpecificOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return travelDS.bus.travelDSServiceImpl.internal_static_travelDS_busSpecific_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return travelDS.bus.travelDSServiceImpl.internal_static_travelDS_busSpecific_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              travelDS.bus.busSpecific.class, travelDS.bus.busSpecific.Builder.class);
    }

    // Construct using travelDS.bus.busSpecific.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      busSpecific_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return travelDS.bus.travelDSServiceImpl.internal_static_travelDS_busSpecific_descriptor;
    }

    @java.lang.Override
    public travelDS.bus.busSpecific getDefaultInstanceForType() {
      return travelDS.bus.busSpecific.getDefaultInstance();
    }

    @java.lang.Override
    public travelDS.bus.busSpecific build() {
      travelDS.bus.busSpecific result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public travelDS.bus.busSpecific buildPartial() {
      travelDS.bus.busSpecific result = new travelDS.bus.busSpecific(this);
      result.busSpecific_ = busSpecific_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof travelDS.bus.busSpecific) {
        return mergeFrom((travelDS.bus.busSpecific)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(travelDS.bus.busSpecific other) {
      if (other == travelDS.bus.busSpecific.getDefaultInstance()) return this;
      if (!other.getBusSpecific().isEmpty()) {
        busSpecific_ = other.busSpecific_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      travelDS.bus.busSpecific parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (travelDS.bus.busSpecific) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object busSpecific_ = "";
    /**
     * <code>string busSpecific = 1;</code>
     */
    public java.lang.String getBusSpecific() {
      java.lang.Object ref = busSpecific_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        busSpecific_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string busSpecific = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBusSpecificBytes() {
      java.lang.Object ref = busSpecific_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        busSpecific_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string busSpecific = 1;</code>
     */
    public Builder setBusSpecific(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      busSpecific_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string busSpecific = 1;</code>
     */
    public Builder clearBusSpecific() {
      
      busSpecific_ = getDefaultInstance().getBusSpecific();
      onChanged();
      return this;
    }
    /**
     * <code>string busSpecific = 1;</code>
     */
    public Builder setBusSpecificBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      busSpecific_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:travelDS.busSpecific)
  }

  // @@protoc_insertion_point(class_scope:travelDS.busSpecific)
  private static final travelDS.bus.busSpecific DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new travelDS.bus.busSpecific();
  }

  public static travelDS.bus.busSpecific getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<busSpecific>
      PARSER = new com.google.protobuf.AbstractParser<busSpecific>() {
    @java.lang.Override
    public busSpecific parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new busSpecific(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<busSpecific> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<busSpecific> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public travelDS.bus.busSpecific getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

