// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bus.proto

package travelDS.bus;

public interface busTimetableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:travelDS.busTimetable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string busTimetable = 1;</code>
   */
  java.lang.String getBusTimetable();
  /**
   * <code>string busTimetable = 1;</code>
   */
  com.google.protobuf.ByteString
      getBusTimetableBytes();
}
