// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bus.proto

package travelDS.bus;

public class travelDSServiceImpl {

  public travelDSServiceImpl() {}

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelDS_busNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelDS_busNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelDS_busTimetable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelDS_busTimetable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelDS_busSpecific_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelDS_busSpecific_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelDS_busAmount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelDS_busAmount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelDS_busDelete_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelDS_busDelete_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tbus.proto\022\010travelDS\"\036\n\tbusNumber\022\021\n\tbu" +
      "sNumber\030\001 \001(\t\"$\n\014busTimetable\022\024\n\014busTime" +
      "table\030\001 \001(\t\"\"\n\013busSpecific\022\023\n\013busSpecifi" +
      "c\030\001 \001(\t\"\036\n\tbusAmount\022\021\n\tbusAmount\030\001 \001(\t\"" +
      "\036\n\tbusDelete\022\021\n\tbusDelete\030\001 \001(\t2\264\001\n\010trav" +
      "elDS\022;\n\014getTimetable\022\023.travelDS.busNumbe" +
      "r\032\026.travelDS.busTimetable\0224\n\006seeBus\022\025.tr" +
      "avelDS.busSpecific\032\023.travelDS.busAmount\022" +
      "5\n\tdeleteBus\022\023.travelDS.busNumber\032\023.trav" +
      "elDS.busDeleteB%\n\014travelDS.busB\023travelDS" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_travelDS_busNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_travelDS_busNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelDS_busNumber_descriptor,
        new java.lang.String[] { "BusNumber", });
    internal_static_travelDS_busTimetable_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_travelDS_busTimetable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelDS_busTimetable_descriptor,
        new java.lang.String[] { "BusTimetable", });
    internal_static_travelDS_busSpecific_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_travelDS_busSpecific_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelDS_busSpecific_descriptor,
        new java.lang.String[] { "BusSpecific", });
    internal_static_travelDS_busAmount_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_travelDS_busAmount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelDS_busAmount_descriptor,
        new java.lang.String[] { "BusAmount", });
    internal_static_travelDS_busDelete_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_travelDS_busDelete_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelDS_busDelete_descriptor,
        new java.lang.String[] { "BusDelete", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
