// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trains.proto

package travelDS.trains;

public interface trainDeleteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:travelDS.trainDelete)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trainDelete = 1;</code>
   */
  java.lang.String getTrainDelete();
  /**
   * <code>string trainDelete = 1;</code>
   */
  com.google.protobuf.ByteString
      getTrainDeleteBytes();
}
