// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trains.proto

package travelDS.trains;

public interface trainNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:travelDS.trainNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trainNumber = 1;</code>
   */
  java.lang.String getTrainNumber();
  /**
   * <code>string trainNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getTrainNumberBytes();
}
