// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trains.proto

package travelDS.trains;

public interface trainTimetableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:travelDS.trainTimetable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trainTimetable = 1;</code>
   */
  java.lang.String getTrainTimetable();
  /**
   * <code>string trainTimetable = 1;</code>
   */
  com.google.protobuf.ByteString
      getTrainTimetableBytes();
}
