// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trains.proto

package travelDS.trains;

public interface trainAmountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:travelDS.trainAmount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trainAmount = 1;</code>
   */
  java.lang.String getTrainAmount();
  /**
   * <code>string trainAmount = 1;</code>
   */
  com.google.protobuf.ByteString
      getTrainAmountBytes();
}
