// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trains.proto

package travelDS.trains;

public interface trainSpecificOrBuilder extends
    // @@protoc_insertion_point(interface_extends:travelDS.trainSpecific)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trainSpecific = 1;</code>
   */
  java.lang.String getTrainSpecific();
  /**
   * <code>string trainSpecific = 1;</code>
   */
  com.google.protobuf.ByteString
      getTrainSpecificBytes();
}
