// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trains.proto

package travelDS.trains;

public final class travelDSServiceImpl {
  private travelDSServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelDS_trainNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelDS_trainNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelDS_trainTimetable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelDS_trainTimetable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelDS_trainSpecific_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelDS_trainSpecific_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelDS_trainAmount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelDS_trainAmount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_travelDS_trainDelete_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_travelDS_trainDelete_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014trains.proto\022\010travelDS\"\"\n\013trainNumber\022" +
      "\023\n\013trainNumber\030\001 \001(\t\"(\n\016trainTimetable\022\026" +
      "\n\016trainTimetable\030\001 \001(\t\"&\n\rtrainSpecific\022" +
      "\025\n\rtrainSpecific\030\001 \001(\t\"\"\n\013trainAmount\022\023\n" +
      "\013trainAmount\030\001 \001(\t\"\"\n\013trainDelete\022\023\n\013tra" +
      "inDelete\030\001 \001(\t2\300\001\n\010travelDS\022?\n\014getTimeta" +
      "ble\022\025.travelDS.trainNumber\032\030.travelDS.tr" +
      "ainTimetable\0228\n\006seeBus\022\027.travelDS.trainS" +
      "pecific\032\025.travelDS.trainAmount\0229\n\tdelete" +
      "Bus\022\025.travelDS.trainNumber\032\025.travelDS.tr" +
      "ainDeleteB(\n\017travelDS.trainsB\023travelDSSe" +
      "rviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_travelDS_trainNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_travelDS_trainNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelDS_trainNumber_descriptor,
        new java.lang.String[] { "TrainNumber", });
    internal_static_travelDS_trainTimetable_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_travelDS_trainTimetable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelDS_trainTimetable_descriptor,
        new java.lang.String[] { "TrainTimetable", });
    internal_static_travelDS_trainSpecific_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_travelDS_trainSpecific_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelDS_trainSpecific_descriptor,
        new java.lang.String[] { "TrainSpecific", });
    internal_static_travelDS_trainAmount_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_travelDS_trainAmount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelDS_trainAmount_descriptor,
        new java.lang.String[] { "TrainAmount", });
    internal_static_travelDS_trainDelete_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_travelDS_trainDelete_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_travelDS_trainDelete_descriptor,
        new java.lang.String[] { "TrainDelete", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
